#version: '3.8'
services:
  mongo:
    image: mongo:5.0
    container_name: mongoDB
    ports:
      - "27018:27017"
    volumes:
      - mongo-db:/data/db
    networks:
      - app-networks
  boot-app:
    #image: batchlcwd/chatback:latest
    image: president7ravi/chatback:latest
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_DATAMONGODB_URI=mongodb://mongo:27017/chatapp
    depends_on:
      - mongo
    networks:
      - app-networks

volumes:
  mongo-db:
networks:
  app-networks:
